# Generated by Django 4.2.16 on 2026-02-02 16:25

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_student_level'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idapplication',
            name='passport',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='passport'),
        ),
        migrations.AlterField(
            model_name='idapplication',
            name='signature',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='signature'),
        ),
        migrations.AlterField(
            model_name='idapplication',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_application', to='students.student'),
        ),
    ]
