# Generated by Django 4.2.16 on 2026-02-06 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_idapplication_passport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idapplication',
            name='signature',
        ),
    ]
