# Generated by Django 4.2.16 on 2026-02-08 14:22

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_idapplication_reviewed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='idapplication',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='idapplication',
            name='passport',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='passport'),
        ),
    ]
