# Generated by Django 6.0.1 on 2026-01-31 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sex',
        ),
    ]
