# Generated by Django 6.0.1 on 2026-01-31 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_student_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
