# Generated by Django 4.2.16 on 2026-02-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='matric_number',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
