# Generated by Django 4.2.16 on 2026-02-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_level_alter_student_matric_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
