# Generated by Django 4.2.16 on 2026-02-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('REVIEWER', 'Reviewer'), ('APPROVER', 'Approver'), ('ADMIN', 'Administrator')], db_index=True, default='STUDENT', max_length=20),
        ),
    ]
