# Generated by Django 6.0.1 on 2026-01-28 22:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcards', '0002_remove_idcard_uuid_alter_idcard_qr_code_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idcard',
            name='qr_code',
        ),
        migrations.AlterField(
            model_name='idcard',
            name='issued_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='idcard',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
