# Generated by Django 6.0.1 on 2026-01-31 22:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcards', '0003_remove_idcard_qr_code_alter_idcard_issued_at_and_more'),
        ('students', '0004_student_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='idcard',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='idcard',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_card', to='students.student'),
        ),
    ]
