# Generated by Django 4.2.16 on 2026-02-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcards', '0004_idcard_uid_alter_idcard_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='idcards/pdfs/'),
        ),
    ]
