# Generated by Django 4.2.16 on 2026-02-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcards', '0005_alter_idcard_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idcard',
            name='uid',
        ),
        migrations.AddField(
            model_name='idcard',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='idcard',
            name='issued_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='idcard',
            name='pdf',
            field=models.FileField(blank=True, upload_to='idcards/pdfs/'),
        ),
    ]
