# Generated by Django 4.2.16 on 2026-02-02 17:53

import cloudinary.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('idcards', '0006_remove_idcard_uid_idcard_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idcard',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='idcard',
            name='pdf',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
