# Generated by Django 6.0.2 on 2026-02-05 17:26

import idcards.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcards', '0007_idcard_uid_alter_idcard_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idcard',
            old_name='issued_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='idcard',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='idcard',
            name='pdf',
        ),
        migrations.AddField(
            model_name='idcard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=idcards.models.idcard_upload_path),
        ),
        migrations.AddField(
            model_name='idcard',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to=idcards.models.passport_upload_path),
        ),
        migrations.AlterField(
            model_name='idcard',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
