# Generated by Django 4.2.16 on 2026-02-06 18:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idcards', '0008_rename_issued_at_idcard_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='idcard',
            name='passport',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
