# Generated by Django 4.2.16 on 2026-02-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcards', '0009_alter_idcard_image_alter_idcard_passport'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='idcard',
            index=models.Index(fields=['uid'], name='idcards_idc_uid_8fe13e_idx'),
        ),
        migrations.AddIndex(
            model_name='idcard',
            index=models.Index(fields=['created_at'], name='idcards_idc_created_4e9f85_idx'),
        ),
    ]
