# Generated by Django 4.2.16 on 2026-02-09 01:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('idcards', '0010_idcard_idcards_idc_uid_8fe13e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idcard',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Disable to invalidate card without deleting'),
        ),
        migrations.AddField(
            model_name='idcard',
            name='is_revoked',
            field=models.BooleanField(default=False, help_text='Revoked cards cannot be verified'),
        ),
        migrations.AddField(
            model_name='idcard',
            name='revoked_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='idcard',
            name='verify_token',
            field=models.CharField(blank=True, db_index=True, help_text='Secure token embedded in QR to prevent forgery', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='idcard',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='idcard',
            index=models.Index(fields=['verify_token'], name='idcards_idc_verify__52c2e2_idx'),
        ),
    ]
