# Generated by Django 4.2.16 on 2026-02-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcards', '0011_idcard_is_active_idcard_is_revoked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idcard',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Card expiry date', null=True),
        ),
        migrations.AlterField(
            model_name='idcard',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='idcard',
            name='is_revoked',
            field=models.BooleanField(default=False),
        ),
    ]
